"""make vendor_id nullable

Revision ID: 01ddf6fb1b24
Revises: ad20260827_serial_lookup_index
Create Date: 2026-08-28 11:42:19.823595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01ddf6fb1b24'
down_revision: Union[str, Sequence[str], None] = 'ad20260827_serial_lookup_index'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods_receipt_notes', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.BigInteger(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods_receipt_notes', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.BigInteger(),
               nullable=False)
    # ### end Alembic commands ###
