"""Add linked_vehicle_codes to api_keys

Revision ID: 52af4d59e364
Revises: 01ddf6fb1b24
Create Date: 2026-08-28 16:51:54.029042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '52af4d59e364'
down_revision: Union[str, Sequence[str], None] = '01ddf6fb1b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_vehicle_codes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('linked_vehicle_codes')
    # ### end Alembic commands ###
